import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
const file=path.join(path.dirname(fileURLToPath(import.meta.url)),"..","data","auditoria-facturas.json");
async function listAll(){try{return JSON.parse(await fs.readFile(file,"utf8"))}catch(error){if(error.code!=="ENOENT")throw error;await fs.writeFile(file,"[]","utf8");return[]}}
export class LocalAuditoriaRepository{
  async save(evento){const datos=await listAll();const registro={id:crypto.randomUUID(),factura_id:evento.facturaId||null,folio_interno:evento.folioInterno||null,folio_origen:evento.folioOrigen||null,accion:evento.accion,usuario_id:evento.usuarioId||null,usuario_nombre:evento.usuarioNombre||null,usuario_email:evento.usuarioEmail||null,detalle:evento.detalle||{},creada_en:new Date().toISOString()};datos.unshift(registro);await fs.writeFile(file,JSON.stringify(datos,null,2),"utf8");return registro}
  async list({accion="",q="",limit=200}={}){const texto=String(q).toLowerCase();return(await listAll()).filter(x=>(!accion||x.accion===accion)&&(!texto||`${x.folio_interno} ${x.folio_origen} ${x.usuario_nombre} ${x.usuario_email}`.toLowerCase().includes(texto))).slice(0,Math.min(Number(limit)||200,500))}
  async resumen({q="",accion="",desde="",hasta="",page=1,pageSize=25}={}){const texto=String(q).toLowerCase(),grupos=new Map();const filtrados=(await listAll()).filter(x=>(!accion||x.accion===accion)&&(!texto||`${x.folio_interno} ${x.folio_origen} ${x.usuario_nombre} ${x.usuario_email}`.toLowerCase().includes(texto))&&(!desde||x.creada_en.slice(0,10)>=desde)&&(!hasta||x.creada_en.slice(0,10)<=hasta));for(const x of filtrados){const clave=x.factura_id||x.folio_interno||x.folio_origen||x.id;const grupo=grupos.get(clave)||{factura_clave:clave,factura_id:x.factura_id,folio_interno:x.folio_interno,folio_origen:x.folio_origen,total_movimientos:0,ultima_accion:x.accion,ultima_fecha:x.creada_en,ultimo_usuario:x.usuario_nombre};grupo.total_movimientos++;if(x.creada_en>grupo.ultima_fecha){grupo.ultima_accion=x.accion;grupo.ultima_fecha=x.creada_en;grupo.ultimo_usuario=x.usuario_nombre}grupos.set(clave,grupo)}const items=[...grupos.values()].sort((a,b)=>b.ultima_fecha.localeCompare(a.ultima_fecha));const limite=Math.min(Math.max(Number(pageSize)||25,1),100),pagina=Math.max(Number(page)||1,1);return{items:items.slice((pagina-1)*limite,pagina*limite),total:items.length,page:pagina,pageSize:limite}}
  async timeline(facturaId){return(await listAll()).filter(x=>x.factura_id===facturaId).sort((a,b)=>a.creada_en.localeCompare(b.creada_en))}
}
