function headers(key,extra={}){return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...extra}}

export class SupabaseAuditoriaRepository{
  constructor({url,serviceRoleKey}){this.root=String(url).replace(/\/$/,"");this.base=`${this.root}/rest/v1/auditoria_facturas`;this.key=serviceRoleKey}
  async request(url,options={}){const response=await fetch(url,{...options,headers:headers(this.key,options.headers)});const text=await response.text();const data=text?JSON.parse(text):null;if(!response.ok)throw new Error(data?.message||data?.error||"No fue posible registrar la bitácora");return data}
  async save(evento){const rows=await this.request(`${this.base}?select=*`,{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({factura_id:evento.facturaId||null,folio_interno:evento.folioInterno||null,folio_origen:evento.folioOrigen||null,accion:evento.accion,usuario_id:evento.usuarioId||null,usuario_nombre:evento.usuarioNombre||null,usuario_email:evento.usuarioEmail||null,detalle:evento.detalle||{}})});return rows[0]}
  async list({accion="",q="",limit=200}={}){const p=new URLSearchParams({select:"*",order:"creada_en.desc",limit:String(Math.min(Math.max(Number(limit)||200,1),500))});const termino=String(q).replace(/[%*(),.]/g,"").trim();if(accion)p.set("accion",`eq.${accion}`);if(termino)p.set("or",`(folio_interno.ilike.*${termino}*,folio_origen.ilike.*${termino}*,usuario_nombre.ilike.*${termino}*,usuario_email.ilike.*${termino}*)`);return this.request(`${this.base}?${p}`)}
  async resumen({q="",accion="",desde=null,hasta=null,page=1,pageSize=25}={}){const limite=Math.min(Math.max(Number(pageSize)||25,1),100);const pagina=Math.max(Number(page)||1,1);const rows=await this.request(`${this.root}/rest/v1/rpc/auditoria_facturas_resumen`,{method:"POST",body:JSON.stringify({p_q:String(q).trim(),p_accion:String(accion).trim(),p_desde:desde||null,p_hasta:hasta||null,p_limit:limite,p_offset:(pagina-1)*limite})});return{items:rows,total:Number(rows[0]?.total_registros||0),page:pagina,pageSize:limite}}
  async timeline(facturaId){const p=new URLSearchParams({select:"*",factura_id:`eq.${facturaId}`,order:"creada_en.asc",limit:"500"});return this.request(`${this.base}?${p}`)}
}
