-- Ejecutar una sola vez en Supabase > SQL Editor.
create table if not exists public.facturas (
  id uuid primary key,
  numero bigint generated by default as identity unique,
  folio_interno text generated always as (
    'NOV-FAC-' || lpad(numero::text, 6, '0')
  ) stored,
  data jsonb not null,
  creada_en timestamptz not null default now(),
  actualizada_en timestamptz not null default now()
);

create index if not exists facturas_creada_en_idx
  on public.facturas (creada_en desc);

alter table public.facturas enable row level security;

-- El backend utiliza la service_role. No se crean políticas públicas para evitar
-- que el navegador pueda leer o modificar información fiscal directamente.
